language: node_js
sudo: false
node_js:
  - "5.3"
before_script:
  - npm i
  - git config --global user.email "denysov.artem@gmail.com"
  - git config --global user.name "TRAVIS-CI"
script:
  - bash ./travis-runner.sh
